name: liveroute_driver
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.5
  flutter_svg: ^2.0.2
  mongo_dart: ^0.9.1
  percent_indicator: ^4.2.3
  buttons_tabbar: ^1.3.6
  intl: ^0.18.0
  flutter_dotenv: ^5.0.2
  mapbox_gl: ^0.16.0
  location: ^4.4.0
  geolocator: ^9.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
    - assets/icon/
